config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do 
    member do 
      get "posts"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, :controller => "post_comments" do
      collection do 
        get :latest
      end
    end
  end


  get "home" => "home#index"
  root :to => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :name

  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title

  has_many :comments
  has_many :post_tagships
  has_many :tags, :through => :post_tagships

  belongs_to :user
end

app/models/post_tagship.rb
class PostTagship < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  delegate :name, :to => :tag, :prefix => true, :allow_nil => true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :name

  has_many :post_tagships
  has_many :posts, :through => :post_tagships
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protect_from_forgery with: :exception

  def index
    if params[:keyword]
      @posts = Post.where( [ "title like ?", "%#{params[:keyword]}%" ] )
    else
      @posts = Post.all
    end
      @posts = @posts.page(params[:page]).per(5)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    sort_by = (params[:order] == 'title') ? 'title' : 'last_commented_at desc'
    @posts = Post.order('created_at DESC').limit(5)
    @comments = Comment.all
  end  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :set_post

  def show
    @comments = @post.comments.page(params[:page]).per(10)

  end

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      @post.update(:last_commented_at => Time.now)
      flash[:notice] = "You have commented successfully!"
      redirect_to post_comment_path(@post, @comment)
    else
      render :action => "new"
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :comment)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, :except => [:index, :new, :create, :latest]

  def index 
    sort_by = (params[:order] == 'title') ? 'title' : 'last_commented_at desc'
    @posts = Post.order(sort_by).page(params[:page]).per(10)
  end

  def show
    @count_comments = Comment.where(:post_id => @post.id).count
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Post was successfully created!"
      redirect_to posts_path
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post was successfully updated!"
      redirect_to post_path(@post)
    else
      render :action => :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post was successfuly deleted!"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :tag_ids => [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    if current_user.update(user_params)
      flash[:notice] = "Profile was successfully updated!"
      redirect_to user_path(current_user)
    else
      render :action => :edit
    end
  end

  def posts
    @posts = current_user.posts
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :gender, :number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="heading">
  <h1>The Popular Forum</h1>
  <h4>Empowered Posts</h4>
</div>  

<%= column_chart @posts.group(:user_id).count %>
<br>
<%= column_chart @posts.group(:created_at).count %>
<br>
<%= column_chart @comments.group(:name).count %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
    <!-- current_user is a method defined by devise to help us check if a user has signed in or not. -->
    <!-- Add below links: -->
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a><%= link_to 'Home', home_path, class:'navbar-brand' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Explore', posts_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">        
      <form class="navbar-form navbar-left">
          <%= form_tag posts_path, :method => :get %>
          <%= text_field_tag "keyword" %>
          <%= submit_tag "Search" %>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
      <% if current_user %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span><i class="glyphicon glyphicon-user"></i></span><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to('My Profile', user_path(current_user)) %></li>
          <li><%= link_to('My Posts', posts_user_path(current_user)) %></li>
          <li><%= link_to('Change Password', edit_user_registration_path) %></li>
          <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign In / Sign Up<span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to('Sign In', new_user_session_path) %></li>
          <li role="separator" class="divider"></li>
          <li>Not a Member?</li>
          <li><%= link_to('Sign Up', new_user_registration_path) %></li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <p style="color: green"><%= flash[:notice] %></p>
	  <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/post_comments/latest.html.erb
<h2>Latest Commented on Posts</h2>
 <ul>
 <% @latest_comments.each do |post| %>
<% @posts.each do |post| %>
<li>
<%= post.title %>
<%= link_to "Show", post_path(post), :method => :get %>
<%= link_to "Edit", edit_post_path(post), :method => :get %>
<%= link_to "Delete", post_path(post), :method => :delete, :data => { :confirm => "Are you sure?"} %>
</li>
<% end %>
</ul>
<% end %>

app/views/post_comments/new.html.erb
<%= form_for @comment, :url => post_comments_path(@post) do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.label :comment %></p>
<p><%= f.text_area :comment %></p>
<p><%= f.submit 'Comment' %></p>
<% end %>

app/views/post_comments/show.html.erb
<ul>
	<% @comments.each do |comment| %>
		<li>
			<p><%= comment.name %> said:</p>
			<p><%= comment.comment %></p>
			<p><%= comment.created_at.strftime('%a, %d %b %Y %H:%M') %></p>
		</li>
	<% end %>
</ul>

<%= link_to 'Comment', new_post_comment_path %>
<p><%= link_to 'Back to post', post_path(@post) %></p>
<%= paginate @comments %>

app/views/posts/_form.html.erb
<p><%= f.label :title, "Title" %></p>
<p><%= f.text_field :title %></p>
<p><%= f.label :body, "Body" %></p>
<p><%= f.text_area :body %></p>
<p><%= f.label :tag_id, "Tag" %></p>
<p><%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) %></p>

app/views/posts/edit.html.erb
<%= form_for @post, :url => post_path(@post) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<p><%= f.submit "Update" %></p>
<% end %>

app/views/posts/index.html.erb
<div class="heading">
  <h1>Posts</h1>
</div>  

<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Sort by
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to 'Title', posts_path(:order => "title") %></li>
    <li><%= link_to 'Last Commented Time', posts_path(:order => "last_commented_at") %></li>
  </ul>
</div>

<% @posts.each do |post| %>
<div class="links">
<%= link_to post_path(post.id) do %>
<div class="container">
  <div class="well">
      <div class="media">
    		<h4 class="media-heading"><%= post.title %></h4>
          <p class="media-body">By <%= post.user.username %></p>
          <p><%= post.body %></p>
          <ul class="list-inline list-unstyled">
            <li><span><i class="glyphicon glyphicon-calendar"></i> <%= (Time.now.to_date - post.created_at.to_date).to_i%> days ago </span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-comment"></i> <%= post.comments.count %> comments</span>
          </ul>
          <i class="glyphicon glyphicon-tags"></i> <%= post.tags.map{ |t| t.name }.join(", ") %></
      </div>
  </div>
</div>
<% end %>
</div>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>
<% end %>


<%= form_for @post, :url => posts_path do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>
	<p><%= f.submit "Create" %></p>
<% end %>

app/views/posts/show.html.erb
<div class="heading">
  <h1><%= @post.title %></h1>
</div>

<div class="post-container">
<p><%= @post.body %></p>

<p><%= button_to "View #{@count_comments} Comments", post_comment_path(@post), :method => :get %></p>

<p>Tags:</p>
<p>
<%= @post.tags.map{ |t| t.name }.join(", ") %>
</p>

<p><%= link_to 'Back to my posts', posts_user_path(current_user) %></p>
</div>

app/views/users/edit.html.erb
<%= form_for current_user, :url => user_path(current_user) do |f| %>
	<p><%= f.label :first_name, "First Name" %></p>
    <p><%= f.text_field :first_name %></p>
    <p><%= f.label :last_name, "Last Name" %></p>
    <p><%= f.text_field :last_name %></p>
    <p><%= f.label :email, "Email" %></p>
    <p><%= f.text_field :email %></p>
    <p><%= f.label :address, "Address" %></p>
    <p><%= f.text_field :address %></p>
    <p><%= f.label :gender, "Gender" %></p>
    <p><%= f.text_field :gender %></p>
    <p><%= f.label :number, "Number" %></p>
    <p><%= f.text_field :number %></p>
	<p><%= f.submit "Update" %></p>
<% end %>

app/views/users/posts.html.erb
<div class="heading">
  <h1>My Posts</h1>
</div> 

<% if @posts.where(:user_id => current_user).count == 0 %>
	<h4>No posts yet :( </h4>
	<%= link_to 'Add new post', new_post_path %>
<% else %>
<% @posts.each do |post| %>
<div class="links">
<%= link_to post_path(post.id) do %>
<div class="container">
  <div class="well">
      <div class="media">
    		<h4 class="media-heading"><%= post.title %></h4>
          <p class="media-body">By <%= post.user.username %></p>
          <p><%= post.body %></p>
          <ul class="list-inline list-unstyled">
            <li><span><i class="glyphicon glyphicon-calendar"></i> <%= (Time.now.to_date - post.created_at.to_date).to_i%> days ago </span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-comment"></i> <%= post.comments.count %> comments</span>
          </ul>
          <i class="glyphicon glyphicon-tags"></i> <%= post.tags.map{ |t| t.name }.join(", ") %></
      </div>
  </div>
</div>
<% end %>
</div>
<% end %>

<% end %>

app/views/users/show.html.erb
<p>First Name: <%= current_user.first_name %></p>
<p>Last Name: <%= current_user.last_name %></p>
<p>Email: <%= current_user.email %></p>
<p>Address: <%= current_user.address %></p>
<p>Gender: <%= current_user.gender %></p>
<p>Number: <%= current_user.number %></p>

<p><%= link_to 'Edit Profile', edit_user_path(current_user) %></p>